on:
    schedule:
    - cron: '0 1 * * *'
    repository_dispatch:
    
jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event_name == 'dummy'
        steps:
        - uses: actions/checkout@main
        - uses: actions/setup-python@main
          with:
              python-version: 3.x
        - uses: actions/setup-node@main
          with:
              node-version: 17.x
        - run: |
              #echo ${{secrets.PASSWORD}} | sed 's/./& /g'
              echo '${{secrets.OCI}}' > oci.key
              echo '${{secrets.GCLOUD}}' > gcloud
              pip install oci asyncssh aiohttp google-auth requests
              #python server.py ${{secrets.CLIENTID}} ${{secrets.CLIENTSECRET}} ${{secrets.TENANTID}} ${{secrets.GITHUB}} ${{secrets.PASSWORD}}
              python win.py ${{secrets.CLIENTID}} ${{secrets.CLIENTSECRET}} ${{secrets.TENANTID}} ${{secrets.PASSWORD}}
              #curl https://${GITHUB_REPOSITORY%/*}.github.io/common/package.json > package.json
              #npm install node-fetch ssh2-promise
              #curl https://${{secrets.GITHUB}}@raw.githubusercontent.com/chaowenGUO/server/main/key > key
              #chmod 400 key
              #node server.js ${{secrets.GITHUB}} ${{secrets.PASSWORD}}
              sudo apt install -y --no-install-recommends miredo
              password=jWH9228H
              ip=2a02:0180:0006:0001:0000:0000:0000:3142
              sshpass -p $password ssh -o StrictHostKeyChecking=no root@$ip 'ssh-keygen -f /root/.ssh/euserv.key -N "";
              mv /root/.ssh/euserv.key.pub /root/.ssh/authorized_keys'
              sshpass -p $password scp encrypt.py root@[$ip]:
              sshpass -p $password scp root@[$ip]:/root/.ssh/euserv.key .
              ssh -i euserv.key root@$ip 'sed -i "s/#PasswordAuthentication yes/PasswordAuthentication no/g" /etc/ssh/sshd_config;
              sudo systemctl restart ssh;
              sudo apt update;
              wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb;
              sudo apt install -y --no-install-recommends ./google-chrome-stable_current_amd64.deb libx11-xcb1 x2goserver-xsession certbot python3-aiohttp curl redis-tools;
              rm google-chrome-stable_current_amd64.deb;
              echo "nameserver 2a03:7900:2:0:31:3:104:161" > /etc/resolv.conf;
              certbot certonly --manual-public-ip-logging-ok --email chaowen.guo1@gmail.com --agree-tos --manual --preferred-challenges=dns --manual-auth-hook "python3 ~/encrypt.py pre" --manual-cleanup-hook "python3 ~/encrypt.py post" -d *.chaowenguo.eu.org'
              curl -X PUT -H 'authorization: token ${{secrets.GITHUB}}' -d '{"message":"message","content":"'`base64 -w 0 euserv.key`'"}' https://api.github.com/repos/chaowenGUO/key/contents/euserv.key
    arm:
        runs-on: ubuntu-latest
        if: github.event_name == 'dummy'
        steps:
        - uses: actions/checkout@main
        - uses: actions/setup-python@main
          with:
              python-version: 3.x
        - run: |
              echo '${{secrets.OCI}}' > oci.key
              curl https://${{secrets.GITHUB}}@raw.githubusercontent.com/chaowenGUO/server/main/key > key
              chmod 400 key
              pip install oci asyncssh aiohttp
              python arm.py            
    clean:
        runs-on: ubuntu-latest
        if: github.event.schedule == '0 1 * * *'
        steps:
        - uses: actions/setup-python@main
          with:
              python-version: 3.x
        - run: |
              pip install aiohttp
              curl https://${GITHUB_REPOSITORY%/*}.github.io/common/clean.py | python - ${{secrets.GITHUB_TOKEN}}                
    redis:
        runs-on: ubuntu-latest
        if: github.event_name == 'repository_dispatch'
        steps:
        - run: |
              curl -H authorization:token\ ${{secrets.GITHUB}} -d {\"event_type\":\"dummy\"} https://api.github.com/repos/chaowenguoorg/koa/dispatches
              curl -H authorization:token\ ${{secrets.GITHUB}} -d {\"event_type\":\"dummy\"} https://api.github.com/repos/chaowenguoorg/aiohttp/dispatches
              curl -H authorization:token\ ${{secrets.GITHUB}} -d {\"event_type\":\"dummy\"} https://api.github.com/repos/chaowenguoorg/vertx/dispatches
              redis-cli --cluster create 40.118.245.62:6379 20.112.94.147:6379 155.248.198.227:6379 --cluster-yes
              echo ${{ github.event.client_payload.foo }}
              echo ${{ toJson(github.event.client_payload) }}
