on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@main
        - env:
              HAHA: ${{secrets.AZURE}}
          run: echo $HAHA > haha
        - uses: actions/upload-artifact@main
          with:
              path: haha
