on:
    push:
    schedule:
    - cron: '0 1 * * *'
    
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - run: |
              sudo apt install -y --no-install-recommends miredo
              sshpass -p JM4HQfVu ssh -o StrictHostKeyChecking=no root@2a02:0180:0006:0001:0000:0000:0000:3142 'rm -rf /root/.ssh;
              ssh-keygen -f /root/.ssh/euserv.key -N "";
              mv /root/.ssh/euserv.key.pub /root/.ssh/authorized_keys'
              sshpass -p JM4HQfVu scp root@[2a02:0180:0006:0001:0000:0000:0000:3142]:/root/.ssh/euserv.key .
              ssh -i euserv.key root@2a02:0180:0006:0001:0000:0000:0000:3142 'sed -i "s/#PasswordAuthentication yes/PasswordAuthentication no/g" /etc/ssh/sshd_config;
              sudo systemctl restart ssh;
              sudo apt update;
              wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb;
              sudo apt install -y --no-install-recommends docker.io ./google-chrome-stable_current_amd64.deb libx11-xcb1 x2goserver-xsession;
              rm google-chrome-stable_current_amd64.deb'
        - uses: actions/upload-artifact@main
          with:
              path: euserv.key
    clean:
        runs-on: ubuntu-latest
        if: github.event.schedule == '0 1 * * *'
        steps:
        - uses: actions/setup-python@main
          with:
              python-version: 3.x
        - run: |
              pip install aiohttp
              curl https://${GITHUB_REPOSITORY%/*}.github.io/common/clean.py | python - ${{secrets.GITHUB_TOKEN}}              
