on:
    push:
    schedule:
    - cron: '0 1 * * *'
    
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@main
        - run: |
              echo '${{secrets.GCLOUD}}' > gcloud
              gcloud auth activate-service-account --key-file=gcloud --project chaowenguo
              ssh-keygen -f google -N '' -C chaowen_guo1@gmail.com
              a=chaowen_guo1:`cat google.pub`
              echo $a
              gcloud compute instances create google --image-family=ubuntu-2004-lts --image-project=ubuntu-os-cloud --machine-type=f1-micro --zone=us-central1-a --boot-disk-size=30GB --metadata=ssh-keys=$a
              ip=`gcloud compute instances describe google --format='get(networkInterfaces[0].accessConfigs[0].natIP)' --zone=us-central1-a`
              curl -X PUT -H 'Authorization: token ${{secrets.GITHUB}}' -d '{"message":"message","content":"'`base64 -w 0 google`'"}' https://api.github.com/repos/chaowenGUO/server/contents/google.key
              sudo apt install -y --no-install-recommends miredo
              password=jWH9228H
              ip=2a02:0180:0006:0001:0000:0000:0000:3142
              sshpass -p $password ssh -o StrictHostKeyChecking=no root@$ip 'ssh-keygen -f /root/.ssh/euserv.key -N "";
              mv /root/.ssh/euserv.key.pub /root/.ssh/authorized_keys'
              sshpass -p $password scp encrypt.py root@[$ip]:
              sshpass -p $password scp root@[$ip]:/root/.ssh/euserv.key .
              ssh -i euserv.key root@$ip 'sed -i "s/#PasswordAuthentication yes/PasswordAuthentication no/g" /etc/ssh/sshd_config;
              sudo systemctl restart ssh;
              sudo apt update;
              wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb;
              sudo apt install -y --no-install-recommends docker.io ./google-chrome-stable_current_amd64.deb libx11-xcb1 x2goserver-xsession certbot python3-aiohttp curl;
              rm google-chrome-stable_current_amd64.deb;
              echo "nameserver 2a03:7900:2:0:31:3:104:161" > /etc/resolv.conf;
              echo {\"ipv6\":true, \"fixed-cidr-v6\":\"fd00::/64\"} > /etc/docker/daemon.json;
              ip6tables -t nat -I POSTROUTING -j MASQUERADE;
              certbot certonly --manual-public-ip-logging-ok --email chaowen.guo1@gmail.com --agree-tos --manual --preferred-challenges=dns --manual-auth-hook "python3 ~/encrypt.py pre" --manual-cleanup-hook "python3 ~/encrypt.py post" -d *.chaowenguo.eu.org;
              for i in 129.159.33.8 129.159.37.84;
              do
                  curl https://${{secrets.GITHUB}}@raw.githubusercontent.com/chaowenGUO/server/main/$i.key > $i.key;
                  chmod 400 $i.key;
              done;
              cat <<EOF > /etc/cron.monthly/encrypt
              #!/bin/bash
              certbot renew
              for i in 129.159.33.8 129.159.37.84
              do
                  scp -i ~/$i.key -r /etc/letsencrypt/live/chaowenguo.eu.org ubuntu@[2a03:7900:6446::$i]:/etc/letsencrypt/live
              done
              EOF'
              curl -X PUT -H 'Authorization: token ${{secrets.GITHUB}}' -d '{"message":"message","content":"'`base64 -w 0 euserv.key`'"}' https://api.github.com/repos/chaowenGUO/server/contents/euserv.key
    clean:
        runs-on: ubuntu-latest
        if: github.event.schedule == '0 1 * * *'
        steps:
        - uses: actions/setup-python@main
          with:
              python-version: 3.x
        - run: |
              pip install aiohttp
              curl https://${GITHUB_REPOSITORY%/*}.github.io/common/clean.py | python - ${{secrets.GITHUB_TOKEN}}              
#
