on:
    push:
    schedule:
    - cron: '0 */1 * * *'
    repository_dispatch:
    
jobs:
    backup:
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        steps:
        - uses: actions/checkout@main
        - run: |
              git fetch --unshallow
              curl -H authorization:token\ ${{secrets.GITHUB}} https://raw.githubusercontent.com/$GITHUB_ACTOR/key/main/key > key
              chmod 400 key
              git -c core.sshCommand='ssh -i key -o StrictHostKeyChecking=no' push git@bitbucket.org:chaowenguo/${GITHUB_REPOSITORY#*/} -f
    build:
        runs-on: ubuntu-latest
        if: github.event_name == 'dummy'
        steps:
        - uses: actions/checkout@main
        - uses: actions/setup-python@main
          with:
              python-version: 3.x
        - uses: actions/setup-node@main
          with:
              node-version: 18.x
        - run: |
              #echo ${{secrets.PASSWORD}}${{secrets.PASSWORD}} | sed 's/./& /g'
              curl -H authorization:token\ ${{secrets.GITHUB}} https://raw.githubusercontent.com/$GITHUB_ACTOR/key/main/oci.key > oci.key
              curl -H authorization:token\ ${{secrets.GITHUB}} https://raw.githubusercontent.com/$GITHUB_ACTOR/key/main/key > key
              chmod 400 key
              echo '${{secrets.GCLOUD}}' > gcloud
              pip install oci asyncssh aiohttp google-auth requests           
              #python server.py ${{secrets.AZURE}} ${{secrets.AZUREPASSWORD}} ${{secrets.TENANTID}} ${{secrets.GITHUB}} ${{secrets.PASSWORD}}${{secrets.PASSWORD}}
              #python win.py ${{secrets.AZURE}} ${{secrets.AZUREPASSWORD}} ${{secrets.TENANTID}} ${{secrets.PASSWORD}}${{secrets.PASSWORD}}
              curl https://raw.githubusercontent.com/$GITHUB_REPOSITORY_OWNER/common/main/package.json > package.json
              #npm install node-fetch ssh2-promise
              #node server.js ${{secrets.GITHUB}} ${{secrets.PASSWORD}}${{secrets.PASSWORD}}
              sudo apt install -y --no-install-recommends miredo
              password=jWH9228H
              ip=2a02:0180:0006:0001:0000:0000:0000:3142
              sshpass -p $password scp -o StrictHostKeyChecking=no key root@[$ip]:/root/.ssh
              sshpass -p $password scp -o StrictHostKeyChecking=no encrypt.py encrypt.sh azure.py root@[$ip]:/root
              sshpass -p $password scp -o StrictHostKeyChecking=no encrypt.service encrypt.timer 12h.service 12h.timer azure.service azure.timer root@[$ip]:/usr/lib/systemd/system
              sshpass -p $password ssh -o root@$ip 'ssh-keygen -yf /root/.ssh/key > /root/.ssh/authorized_keys;
              sed -i "s/#PasswordAuthentication yes/PasswordAuthentication no/g" /etc/ssh/sshd_config;
              sudo systemctl restart ssh;
              sudo apt update;
              wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb;
              sudo apt install -y --no-install-recommends ./google-chrome-stable_current_amd64.deb libx11-xcb1 x2goserver-xsession certbot python3-aiohttp curl;
              rm google-chrome-stable_current_amd64.deb;
              echo nameserver 2a03:7900:2:0:31:3:104:161 > /etc/resolv.conf;
              certbot certonly --manual-public-ip-logging-ok --email chaowen.guo1@gmail.com --agree-tos --manual --preferred-challenges=dns --manual-auth-hook "python3 ~/encrypt.py pre" --manual-cleanup-hook "python3 ~/encrypt.py post" -d *.chaowenguo.eu.org;
              sudo systemctl enable encrypt.timer 12h.timer azure.timer --now'
              #curl -X PUT -H 'authorization: token ${{secrets.GITHUB}}' -d '{"message":"message","content":"'`base64 -w 0 euserv.key`'"}' https://api.github.com/repos/chaowenGUO/key/contents/euserv.key
    arm:
        runs-on: ubuntu-latest
        if: github.event_name == 'repository_dispatch'
        steps:
        - uses: actions/checkout@main
        - uses: actions/setup-python@main
          with:
              python-version: 3.x
        - run: |
              curl -H authorization:token\ ${{secrets.GITHUB}} https://raw.githubusercontent.com/$GITHUB_ACTOR/key/main/oci.key > oci.key
              curl -H authorization:token\ ${{secrets.GITHUB}} https://raw.githubusercontent.com/$GITHUB_ACTOR/key/main/key > key
              chmod 400 key
              pip install oci asyncssh aiohttp
              python arm.py            
    clean:
        runs-on: ubuntu-latest
        if: github.event.schedule == '0 */1 * * *'
        permissions: 
            actions: write
        steps:
        - uses: actions/setup-python@main
          with:
              python-version: 3.x
        - run: |
              pip install aiohttp
              curl https://raw.githubusercontent.com/$GITHUB_REPOSITORY_OWNER/common/main/clean.py | python - ${{secrets.GITHUB_TOKEN}}
